services:
  db:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: springboot
      MYSQL_DATABASE: personal_website
      MYSQL_USER: root
      MYSQL_PASSWORD: springboot
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql   # 添加此行以實現資料持久化
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/personal_website
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: springboot
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:   # 定義一個命名卷 mysql_data
