version: "3.8"

services:
  db:
    image: mysql:8.0.22
    container_name: joe-personal-website-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: springboot
      MYSQL_DATABASE: personal_website
      MYSQL_USER: root
      MYSQL_PASSWORD: springboot
    ports:
      - "3307:3306"  # 讓本機透過 localhost:3307 連接 MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: joe-personal-website-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker  # 讓 Spring Boot 自動讀取 application-docker.properties
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
